# Generated by Django 2.1.7 on 2019-02-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(max_length=10, verbose_name='Band')),
                ('bssid', models.CharField(max_length=30, verbose_name='BSSID')),
                ('channel', models.CharField(max_length=10, verbose_name='Channel')),
                ('frequency', models.IntegerField(verbose_name='Frequency')),
                ('rates', models.CharField(max_length=30, verbose_name='Rates')),
                ('rssi', models.IntegerField(verbose_name='RSSI')),
                ('security', models.CharField(max_length=10, verbose_name='Security')),
                ('ssid', models.CharField(max_length=50, verbose_name='SSID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Time Stamp')),
                ('vendor', models.CharField(max_length=50, verbose_name='Vendor')),
                ('width', models.CharField(max_length=5, verbose_name='Width')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_file', models.FileField(max_length=40, upload_to='', verbose_name='Upload file with device information')),
                ('latitude', models.DecimalField(decimal_places=1, max_digits=3)),
                ('longitude', models.DecimalField(decimal_places=1, max_digits=3)),
                ('accuracy', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
    ]
